-- award DML.sql

--------------data tblaward-----------------
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'황금촬영상','최우수 남우조연상',1);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'한국영화제작가협회상','남우주연상',1);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'MTV 영화 & TV 상','최고의배우상-영화',2);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'아카데미시상식','음향상',2);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'아카데미시상식','시각효과상',3);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'새틀라이트시상식','감독상',3);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'백상예술대상','영화 남자조연상',4);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'황금촬영상','촬영상-금상',4);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'대종상영화제','여우조연상',5);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'MTV 영화 & TV 상','최고의 악당상',6);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'백상예술대상','영화 예술상',7);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'황금촬영상','편집상',7);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'한국영화평론가협회상','남우주연상',8);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'백상예술대상','영화 신인감독상',8);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'아카데미시상식','의상상',13);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'골든글로브시상식','여우조연상',13);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'아시아필름어워즈','여우조연상',14);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'한국영화제작가협회상','남우조연상',14);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'MTV 영화 & TV 상','최고의 영화상',15);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'MTV 영화 & TV 상','최고의 배우상-영화',15);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'백상예술대상','영화 여자조연상',16);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'피렌체 한국영화제','관객상',16);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'백상예술대상','영화대상',17);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'백상예술대상','여자최우수연기상',17);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'백상예술대상','영화감독상',17);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'황금촬영상','시각효과상',18);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'대종상영화제','미술상',18);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'아시아필름어워즈','감독상',21);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'황금촬영상','신인여우상',21);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'대종상영화제','여우주연상',23);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'대종상영화제','음악상',23);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'대종상영화제','뉴웨이브상 남우',23);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'워싱턴비평가협회상','음악상',24);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'황금촬영상','최우수 작품상',30);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'대종상영화제','감독상',30);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'청룡영화상','미술상',30);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'판타스포르토국제영화제','감독주간경쟁-감독상',31);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'일본아카데미상','신인배우상',34);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'피렌체 한국영화제','마이무비상',38);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'부산영화평론가협회상','신인남자연기자상',38);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'청룡영화상','신인남우상',38);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'골든라즈베리시상식','최악의 남우주연상',41);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2023,'골든라즈베리시상식','최악의 여우조연상',41);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'시체스국제판타스틱영화제','오피셜 판타스틱-심사위원특별상',42);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'부천국제판타스틱영화제','저 세상 패밀리상',43);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'황금촬영상','아역상',44);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'판타지아국제영화제','특별언급-슈발누아경쟁',44);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'뉴욕비평가협회상','여우조연상',46);
INSERT INTO TBLAWARD VALUES (AWARDSEQ.nextVal,2022,'백상예술대상','영화 남자신인연기상',50);



